import { InMemoryDbService } from 'angular-in-memory-web-api';

import { IHotel } from '../models/hotel';

/**
 * Initial data for in memory web api
 *
 * @export
 * @class HotelData
 * @implements {InMemoryDbService}
 */
export class HotelData implements InMemoryDbService {

  createDb(): Record<string, IHotel[]> {
    const hotels: IHotel[] = [
      
        {
            id: 1, 
            hotelName: "Buea sweet life",
            description:"Belle vue au bord de la mer",
            price: 230.5,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/the-interior.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/indoors.jpg",
            imageUrl4: "assets/img/hotel-room.jpg",
            cityName: "Yaoundé",
            quartier: "Emana", 
            type: "appartement",
            categorie: "meublés",
            rating: 3.5
      },
      {
            id: 2,
            hotelName: "Marakech",
            description:"Profitez de la vue sur les montagnes",
            price: 145.5,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/the-interior.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/hotel-room.jpg",
            cityName: "Yaoundé",
            quartier: "Damas",
            type: "appartement",
            categorie: "meublés",
            rating: 5
      },
      {
            id: 3,
            hotelName: "Abudja new look palace",
            description:"Séjour complet avec service de voitures",
            price: 120.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/indoors.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Simbock",
            type: "studio",
            categorie: "meublés",
            numerowhatsappOne: 651949981,
            numerowhatsappTwo: 655555555,
            rating: 4
      },
      {
            id: 4,
            hotelName: "Cape town city",
            description:"Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Mendong",
            type: "chambre",
            categorie: "meublés",
            rating: 2.5
      },
      {
            id: 5,
            hotelName: "Bamao city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Akwa",
            type: "chambre",
            categorie: "meublés",
            rating: 4.5
      },
      {
            id: 6,
            hotelName: "Nairobie city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Akwa",
            type: "studio",
            categorie: "meublés",
            rating: 5
      },
      {
            id: 7,
            hotelName: "Tokyo city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "New-bell",
            type: "chambre",
            categorie: "meublés",
            rating: 4.5
      },
      {
            id: 8,
            hotelName: "Berlin city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "New-bell",
            type: "studio",
            categorie: "meublés",
            rating: 4
      },
      {
            id: 9,
            hotelName: "Lyon city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Dakar",
            type: "chambre",
            categorie: "meublés",
            rating: 3.5
      },
      {
            id: 10,
            hotelName: "Toulouse city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Dakar",
            type: "appartement",
            categorie: "meublés",
            rating: 3
      },
      {
            id: 11,
            hotelName: "English city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Village",
            type: "appartement",
            categorie: "meublés",
            rating: 2.5
      },
      {
            id: 12,
            hotelName: "French city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Village",
            categorie: "meublés",
            type: "studio",
            rating: 2
      },
      {
            id: 13,
            hotelName: "British city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Akwa",
            type: "studio",
            categorie: "meublés",
            rating: 1.5
      },
      {
            id: 14,
            hotelName: "Montreal city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Emana",
            type: "chambre",
            categorie: "non meublés",
            rating: 1
      },
      {
            id: 15,
            hotelName: "Quebec city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Mendong",
            type: "studio",
            categorie: "non meublés",
            rating: 0.5
      },
      {
            id: 16,
            hotelName: "Ottawa city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Simbock",
            type: "appartement",
            categorie: "non meublés",
            rating: 1
      },
      {
            id: 17,
            hotelName: "Kigali city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Simbock",
            type: "appartement",
            categorie: "non meublés",
            rating: 1.5
      },
      {
            id: 18,
            hotelName: "Paris city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Akwa",
            type: "appartement",
            categorie: "non meublés",
            rating: 2
      },
      {
            id: 19,
            hotelName: "Den city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "Village",
            type: "chambre",
            categorie: "non meublés",
            rating: 2.5
      },
      {
            id: 20,
            hotelName: "Denver city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "New-bell",
            type: "studio",
            categorie: "non meublés",
            rating: 3
      },
      {
            id: 21,
            hotelName: "Blessing city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Douala",
            quartier: "New-bell",
            type: "chambre",
            categorie: "non meublés",
            rating: 4
      },
      {
            id: 22,
            hotelName: "Love city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Damas",
            type: "chambre",
            categorie: "non meublés",
            rating: 4.5
      },
      {
            id: 23,
            hotelName: "New city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Damas",
            type: "studio",
            categorie: "non meublés",
            rating: 5
      },
      {
            id: 24,
            hotelName: "Gold city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Bonas",
            type: "appartement",
            categorie: "non meublés",
            rating: 4.5
      },
      {
            id: 25,
            hotelName: "Eden city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Bonas",
            type: "studio",
            categorie: "non meublés",
            rating: 4
      },
      {
            id: 26,
            hotelName: "New-York city",
            description: "Magnifique cadre pour votre séjour",
            price: 135.12,
            numberOne: 651949981,
            numberTwo: 695637555,
            imageUrl: "assets/img/window.jpg",
            imageUrl1: "assets/img/the-interior.jpg",
            imageUrl2: "assets/img/indoors.jpg",
            imageUrl3: "assets/img/hotel-room.jpg",
            imageUrl4: "assets/img/indoors.jpg",
            cityName: "Yaoundé",
            quartier: "Bonas",
            type: "chambre",
            categorie: "non meublés",
            rating: 3.5
      }
    
    ];

    return { hotels };
  }


  genId(hotels: IHotel[]): number {
    return hotels.length > 0 ? Math.max(...hotels.map(hotel => hotel.id)) + 1 : 1;
  }
}
